### PR TITLE
finished path planner

### PR DESCRIPTION
**Pull request by 31415us**
sorry for big pr, take your time to review. there are unit tests for most of the functionality

### CODE REVIEW

**Comment by SyrianSpock** [comment]
Could you document a simple usage example, so we can test it out with artificial data ?
Thanks

**Comment by 31415us** [comment]
for now there's a visualizer.py in the root folder which directly calls molly and plots the generated trajectory. i'll try to make it a bit more intuitive and document it better

**Comment by SyrianSpock** [comment]
Ok.
A very short paragraph about that in the Readme would suffise ;)

**Comment by antoinealb** [comment]
I see one more "fix bug" commit. Is that stable now ? can we merge and call it done ?

**Comment by 31415us** [comment]
there is still one known issue when checking for collision with polygon obstacles, there is a temporary fix not yet commited. i will update the readme in the next few days. apart from the known issue the api is stable and can be integrated

**Pull request merged**
